// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtOzvRt4cweTV9sC6LzDb4iHWKVjBFkQc',
    appId: '1:301521655323:web:951e7b80a327ee2af90abe',
    messagingSenderId: '301521655323',
    projectId: 'plantake-charmai',
    authDomain: 'plantake-charmai.firebaseapp.com',
    storageBucket: 'plantake-charmai.appspot.com',
    measurementId: 'G-DCPDBHX397',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7lFi4p_lLG-fgo_eRldT-UNChRYcTbiU',
    appId: '1:301521655323:android:c6c5e1296afaa0b3f90abe',
    messagingSenderId: '301521655323',
    projectId: 'plantake-charmai',
    storageBucket: 'plantake-charmai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQYS0ep48WPXFc4kXs2oticytXmPG-20',
    appId: '1:301521655323:ios:fb14018d12f32dc6f90abe',
    messagingSenderId: '301521655323',
    projectId: 'plantake-charmai',
    storageBucket: 'plantake-charmai.appspot.com',
    iosBundleId: 'com.example.rizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQYS0ep48WPXFc4kXs2oticytXmPG-20',
    appId: '1:301521655323:ios:267227200086dd2ef90abe',
    messagingSenderId: '301521655323',
    projectId: 'plantake-charmai',
    storageBucket: 'plantake-charmai.appspot.com',
    iosBundleId: 'com.example.rizz.RunnerTests',
  );
}
